#obj-m := bmi_bugduino.o
#	KDIR := ../../../..
#	PWD := $(shell pwd)
#default:
#	$(MAKE) -C $(KDIR) SUBDIRS=$(PWD) modules
#clean:
#	rm -f *.mod.c *.ko *.o


#
# BMI PIMS
#

obj-$(CONFIG_BMI_BUGDUINO)		+= bmi_bugduino_core.o
bmi_bugduino_core-objs := bmi_bugduino.o

