#
# BMI PIMS
#

obj-$(CONFIG_BUG_FACTORY_TEST)	+= factory_test/
obj-$(CONFIG_BMI_GPS)		+= gps/
obj-$(CONFIG_BMI_MDACC)		+= mdacc/
obj-$(CONFIG_BMI_LCD)	+= lcd/
obj-$(CONFIG_BMI_VIDEO)	+= video/
obj-$(CONFIG_BMI_CAMERA)	+= camera/
obj-m                     	+= camera/
obj-$(CONFIG_BMI_AUDIO)		+= sound/
obj-$(CONFIG_BMI_VH)		+= vonhippel/
obj-$(CONFIG_BMI_GSM)		+= gsm/
obj-$(CONFIG_BMI_SENSOR)	+= sensor/
obj-$(CONFIG_VIDEO_BMI_PROJECTOR)	+= projector/
obj-$(CONFIG_BMI_ZB)		+= zb/
obj-$(CONFIG_BMI_ACCNT)		+= accenture/

