#ifeq ($(CONFIG_MACH_BUG),y)
#	obj-$(CONFIG_BMI_CAMERA) += bug_v4l2_capture.o 
#endif

#obj-$(CONFIG_BMI_CAMERA) += bug_camera.o
#
#bmi_camera_vs6624-objs := bmi_vs6624.o vs6624_access.o
#obj-$(CONFIG_BMI_CAMERA_VS6624) += bmi_camera_vs6624.o
#
#bmi_camera_ov2640-objs := bmi_ov2640.o ov2640.o
#obj-$(CONFIG_BMI_CAMERA_OV2640) += bmi_camera_ov2640.o

obj-$(CONFIG_BMI_CAMERA) += bmi_camera.o

obj-$(CONFIG_BMI_CAMERA_LI3M02CM) += bmi_li3m02cm.o mt9t111.o